### ISSUE TITLE
minimum algorithms spec'd for IAK and IDevID key-pair generation

### ISSUE THREAD

**Issue by sulrich** [openconfig/attestz#11]
apologies for missing the PR discussion previously.  @jenia-grunin suggested that i open this issue here. 

pull #9 ([as merged](https://github.com/openconfig/attestz/blob/307cbe9c2fc14382905d61277c929e9ac978a14f/README.md?plain=1#L50-L53)) updates the text to specify the preferred/minimum algorithms for IAK and IDevID key-pairs.

it bears noting that many shipping and deployed 2.0 TPMs will not meet this specification.  the original PR text (something to the effect of: "vendors should use the strongest crypto algorithms supported by the TPM") seemed to be in keeping with the philosophic intent without being overly prescriptive regarding operation.

**Comment by jenia-grunin** [comment]
Thanks for raising this, Steve! As discussed offline and in https://buganizer.corp.google.com/issues/319859433, the latest TCG spec https://trustedcomputinggroup.org/wp-content/uploads/PC-Client-Specific-Platform-TPM-Profile-for-TPM-2p0-v1p05p_r14_pub.pdf makes it mandatory to only support ECC P384, RSA 3072 and SHA 384, while ECC P521, RSA 4096 and SHA-512 are optional. Even though our preference is still ECC P521, it is understandable that TPM firmware upgrade (allowing the support of more advanced algos) process may be complicated or infeasible in the nearest future. I will discuss this more broadly internally and with other vendors, but I think that relying on ECC-P384 IAK and IDevID (and possibly EK), SHA-384 PCR selection bank and SHA-384 digest for PCR quote (even though the default seems to be SHA-256) should be reasonable and offers a happy compromise for all of us. Please let me know if this would work well for you. I will update the README once we finalize on the decision with everyone.

**Comment by jenia-grunin** [comment]
Hey, Steve,

I have sent https://github.com/openconfig/attestz/pull/18 with the latest update. Please let me know what you think and if you have any questions/concerns! Hope this helps :)

Jenia

**Comment by sulrich** [comment]
thanks for the update. i  think this hits the mark nicely.
